services:
  - type: web
    name: codeinsync-server
    rootDir: server
    env: node
    plan: free
    region: oregon
    autoDeploy: true
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: CLIENT_ORIGIN
        sync: false
